# Generated by Django 2.0.8 on 2018-08-21 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='access_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasource',
            name='users_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasource', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='users_group_requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasource_requested', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Data providers'}, on_delete=django.db.models.deletion.PROTECT, related_name='datasources', to=settings.AUTH_USER_MODEL),
        ),
    ]
