# Generated by Django 2.0.8 on 2018-08-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_remove_groups_from_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='plugin_name',
            field=models.CharField(default='IoTUK', max_length=63),
            preserve_default=False,
        ),
    ]
