# Generated by Django 2.0.8 on 2018-10-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0006_one_to_one_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='api_key',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
