# Generated by Django 2.0.8 on 2018-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0007_datasource_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='_connector_string',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
