# Generated by Django 2.0.8 on 2018-11-08 09:29

import datasources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0011_datasource_permissions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionlink',
            name='reason',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='userpermissionlink',
            name='granted',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'VIEW'), (2, 'META'), (3, 'DATA'), (4, 'PROV')], default=datasources.models.UserPermissionLevels(0)),
        ),
        migrations.AlterField(
            model_name='userpermissionlink',
            name='requested',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'VIEW'), (2, 'META'), (3, 'DATA'), (4, 'PROV')], default=datasources.models.UserPermissionLevels(0)),
        ),
    ]
