# Generated by Django 2.0.8 on 2018-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0012_add_request_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasource',
            name='encrypted_docs_url',
            field=models.URLField(blank=True, verbose_name='Documentation URL for managing encrypted data'),
        ),
    ]
