# Generated by Django 2.0.8 on 2018-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0014_access_control_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='prov_exempt',
            field=models.BooleanField(default=False, help_text='Should this data source be exempt from PROV tracking? This is useful for utility data sources which expect a large volume of queries, but are not interested in analysing usage patterns.'),
        ),
    ]
