# Generated by Django 2.0.8 on 2018-12-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0014_access_control_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=511)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_items', to='datasources.DataSource')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='datasources.MetadataField')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metadataitem',
            unique_together={('field', 'datasource')},
        ),
    ]
