# Generated by Django 2.0.8 on 2018-12-07 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0015_add_dynamic_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafield',
            name='short_name',
            field=models.CharField(default='', max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_]*\\Z', 'Short name must begin with a letter and consist only of letters, numbers and underscores.', 'invalid')]),
            preserve_default=False,
        ),
    ]
