# Generated by Django 2.0.8 on 2018-12-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0016_prov_exempt_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='external_requests',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='datasource',
            name='external_requests_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
