# Generated by Django 2.0.8 on 2018-12-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0017_count_external_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='auth_method',
            field=models.IntegerField(choices=[('NONE', -1), ('UNKNOWN', 0), ('BASIC', 1), ('HEADER', 2)], default=0),
        ),
    ]
