# Generated by Django 2.0.8 on 2019-01-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0019_auth_method_swap_key_value'),
        ('datasources', '0016_metadatafield_short_name'),
    ]

    operations = [
    ]
