# Generated by Django 2.0.8 on 2019-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0022_datasource_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
