# Generated by Django 2.0.8 on 2019-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0023_relax_url_to_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafield',
            name='operational',
            field=models.BooleanField(default=False),
        ),
    ]
