# Generated by Django 2.0.8 on 2019-01-25 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0024_metadatafield_operational'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissionlink',
            unique_together={('user', 'datasource')},
        ),
    ]
