# Generated by Django 2.0.8 on 2019-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0025_unique_together_permission_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionlink',
            name='push_data',
            field=models.BooleanField(default=False),
        ),
    ]
