# Generated by Django 2.0.8 on 2019-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0026_userpermissionlink_push_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissionlink',
            old_name='push_data',
            new_name='push_requested',
        ),
        migrations.AddField(
            model_name='userpermissionlink',
            name='push_granted',
            field=models.BooleanField(default=False),
        ),
    ]
