# Generated by Django 2.0.8 on 2019-01-30 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0028_add_licence_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Data providers'}, on_delete=django.db.models.deletion.PROTECT, related_name='licences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
