# Generated by Django 2.0.8 on 2019-01-30 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0029_license_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='License',
            new_name='Licence',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='license',
            new_name='licence',
        ),
    ]
