# Generated by Django 2.0.8 on 2019-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0030_rename_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='plugin_name',
            field=models.CharField(default='DataSetConnector', max_length=63),
        ),
    ]
