# Generated by Django 2.0.13 on 2019-04-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0032_add_quality_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualitycriterion',
            options={'verbose_name_plural': 'quality criteria'},
        ),
        migrations.AlterModelOptions(
            name='qualitylevel',
            options={'ordering': ['level']},
        ),
    ]
