# Generated by Django 2.0.13 on 2019-04-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0033_quality_levels_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'Data providers'}, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(default='NullPipelineStage', max_length=63)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasources.Pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datasources.Pipeline'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='pipelinestage',
            order_with_respect_to='pipeline',
        ),
    ]
