# Generated by Django 2.0.13 on 2019-04-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0034_create_pipeline_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datasources.Pipeline'),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='datasources.Pipeline'),
        ),
    ]
