# Generated by Django 2.0.8 on 2018-11-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('type', models.CharField(choices=[('aca', 'Academic'), ('bus', 'Business'), ('cha', 'Charity'), ('gov', 'Government'), ('oth', 'Other')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superauditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='profiles.Institution'),
        ),
    ]
