# Generated by Django 2.0.8 on 2018-11-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_institution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='OrganisationalUnit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='institution',
            new_name='organisational_unit',
        ),
    ]
