# Generated by Django 2.0.8 on 2018-08-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_limit_owner_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(editable=False, limit_choices_to={'groups__name': 'Application providers'}, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
