# Generated by Django 2.0.8 on 2018-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_owner_from_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='access_control',
            field=models.BooleanField(default=False),
        ),
    ]
