# Generated by Django 2.0.8 on 2018-09-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('applications', '0004_application_access_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='users_group',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='application',
            name='users_group_requested',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group'),
        ),
    ]
