# Generated by Django 2.0.8 on 2018-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_one_to_one_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
