# Generated by Django 2.0.8 on 2018-11-01 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_unset_url_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='proxy_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_proxy', to=settings.AUTH_USER_MODEL),
        ),
    ]
