# Generated by Django 2.0.8 on 2019-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_proxy_user_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
