# Generated by Django 2.0.8 on 2018-08-29 12:26

from django.db import migrations, models
import djongo.models.fields
import prov.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('related_pk', models.PositiveIntegerField()),
                ('entries', djongo.models.fields.ArrayModelField(blank=True, default=[], model_container=prov.models.ProvEntry, null=False)),
            ],
        ),
    ]
