# Generated by Django 2.0.8 on 2018-08-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provcollection',
            name='app_label',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='provcollection',
            name='model_name',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
